### PR TITLE
Adamc/decouple rosstore with sub and pub

### PR DESCRIPTION
**Pull request by adamseth2**
Tried to move useRoslib store to only hold state, while functionality was moved to another place that doesn't directly involve state is moved in roslibUtils

Turns out classes don't work with reactive in Vue, so instead used functions to return objects.

Also did some general cleanup with comments and naming

### CODE REVIEW

**Comment by uellenberg** [comment]
@adamseth2 I think we should merge in the I-Love-UWB branch instead (once we fix it up, a bit). The problem is that this code breaks heartbeats, doesn't contain the camera code (I know master doesn't either, but I-Love-UWB does), and contains additional modifications to the roslib interfaces.

**Comment by adamseth2** [comment]
Saw changes on I-love-UWB, will look over it later and add some changes on the camera side.

**Comment by uellenberg** [comment]
Here's my branch: https://github.com/TrickfireRobotics/mission-control/commits/uellenberg/i-love-uwb-cleanup/

I modified the typings for subscribers to make them consistent with the behavior of the code. I also did some general cleanup and documentation. It would be great to get this merged all at once so that future changes don't need to deal with the roslib stuff changes. Let's see if we can get all of these outstanding changes merged during the meeting today!

**Comment by uellenberg** [comment]
Old commit hash: [04b0d0f](https://github.com/TrickfireRobotics/mission-control/pull/38/commits/04b0d0f8a05a817a060f5711e1d8337535ca961a)

**Review by uellenberg — APPROVED** [review]

**Pull request merged**
