### PR TITLE
Fix and run eslint + prettier

### PR DESCRIPTION
**Pull request by uellenberg**
This fixes eslint's config and does a pass through with eslint and prettier. I also manually fixed up some issues, although there are still a few left.

### CODE REVIEW

**Comment by adamseth2** [comment]
Looks good, I would not recommend merging yet until all the other PQs are merged as this will likely cause a headache amount of merge conflicts and I would then rebase then run prettier and eslint one more time.

**Comment by uellenberg** [comment]
> Looks good, I would not recommend merging yet until all the other PQs are merged as this will likely cause a headache amount of merge conflicts and I would then rebase then run prettier and eslint one more time.

@adamseth2 It honestly might be better to merge this right away, so that we can merge it into any current work and run the formatter on it. The history might get a little gross, but we won't have to synchronize everything. Unless we expect to be able to merge everything soon and not have any outstanding work for a little bit, we'll have to deal with the merge conflicts anyway.

I think any way we do it, it's not going to be super awesome to merge this. Moving forward, we should make sure that our IDEs run the formatter and linter automatically.

**Comment by uellenberg** [comment]
Step 1: Merge eslint changes into master.
Step 2: For all active branches:
```bash
git checkout master
git pull
git checkout <my_branch>
git merge master
# Fix merge conflicts, then git commit
git push
```

Step 3: Merge format run.

Step 4: For all active branches:
```bash
git checkout master
git pull
git checkout <my_branch>
git merge -s ours master
# There shouldn't be any merge conflicts here
git push
```

**Review by VladimirKupryukhin — APPROVED** [review]
LGTM

**Comment by uellenberg** [comment]
Here's the process for every active branch:
```bash
git checkout master
git pull
npm i

# For each branch:
git checkout <my_branch>
git merge 149250096d8c304a625755d98bfa784a83349149
# Fix merge conflicts, then git commit
git merge -s ours master
# There shouldn't be any merge conflicts here
npm run format
npm run lint
git commit -m "Run formatter and linter"
git push
```

**Pull request merged**
